#ifndef NUMBERS_H_INCLUDED
#define NUMBERS_H_INCLUDED

#define number11 "Í» "
#define number12 " º "
#define number13 " º "
#define number14 " º "
#define number15 "ÍÊÍ"
#define number21 "ÍÍ»"
#define number22 "  º"
#define number23 "ÉÍ¼"
#define number24 "º  "
#define number25 "ÈÍÍ"
#define number31 "ÍÍ»"
#define number32 "  º"
#define number33 "ÍÍ¹"
#define number34 "  º"
#define number35 "ÍÍ¼"
#define number41 "º º"
#define number42 "º º"
#define number43 "ÈÍ¹"
#define number44 "  º"
#define number45 "  º"
#define number51 "ÉÍÍ"
#define number52 "º  "
#define number53 "ÈÍ»"
#define number54 "  º"
#define number55 "ÍÍ¼"
#define number61 "ÉÍ»"
#define number62 "º  "
#define number63 "ÌÍ»"
#define number64 "º º"
#define number65 "ÈÍ¼"
#define number71 "ÉÍ»"
#define number72 "  º"
#define number73 "  º"
#define number74 "  º"
#define number75 "  º"
#define number81 "ÉÍ»"
#define number82 "º º"
#define number83 "ÌÍ¹"
#define number84 "º º"
#define number85 "ÈÍ¼"
#define number91 "ÉÍ»"
#define number92 "º º"
#define number93 "ÈÍ¹"
#define number94 "  º"
#define number95 " Í¼"

#endif // NUMBERS_H_INCLUDED
